### ISSUE TITLE
Bug? Viewing other registered members for activity after it happend

### ISSUE THREAD

**Issue by KnightsSecret** [esrg-knights/Squire#87]
Hi all,
I wanted to give you guys en example for why i made Issue #82 , but when i looked at the page of the boardgame evening of yesterday, while being logged in, i could not see the name of the other registrants anymore
https://app.kotkt.nl/calendar/slots/1?date=2020-10-13T17%3A30%3A00.000Z
![image](https://user-images.githubusercontent.com/72865919/95989791-037f7780-0e2b-11eb-9a0c-2f8bcbe45805.png)

**Comment by EricTRL** [comment]
That is (partially) intentional. It is currently not possible for anyone to see the participants of activities that took place in the past (due to privacy reasons).
In the future, we'll be updating the permission system (#30) so that board members (or anyone else with that permission) can still see participants after activities have taken place. For now, it's still possible for board members to see participants of activites in the admin panel (which is not too ideal).

**Comment by KnightsSecret** [comment]
Oké than this might be handeld as resolved and then i know the short time work around.
